### ISSUE TITLE
2 OpenArenas at flathub

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/io.github.ec_.Quake3e.OpenArena#53] opened 2023-09-01 08:51 UTC
Hi,

currently you can find two OpenArenas ( OpenArena (Quake3e) and OpenArena ) at Flathub which look almost identical. Could you get in contact with [ws.openarena.OpenArena](https://github.com/flathub/ws.openarena.OpenArena) to sync the two manifests in order to provide only one OpenArena at flathub? This would help avoid any confusion for potential users.

Regards
Jakob

**Comment by AsciiWolf** [comment] 2023-09-01 12:38
io.github.ec_.Quake3e.OpenArena as far as I know is actually a fork of OpenArena while ws.openarena.OpenArena is the original one (including the original engine version, assets etc.).

**Comment by AsciiWolf** [comment] 2023-09-18 10:20
However, since the original OpenArena version is really outdated now, it could be a good idea to consider merging the two Flatpaks (EOLing the original one, adding me as a co-maintainer of this repo and renaming this Flatpak in AppStream metadata to "OpenArena" - without the " Quake3e" suffix).

@xplshn What is your opinion about this?

**Comment by xplshn** [comment] 2023-10-12 03:09
Yeah, however, I don't know how to approach to them about this. I need clarification to also know if openarena is still alive too...

**Comment by AsciiWolf** [comment] 2023-10-12 09:16
The original OpenArena Flatpak is maintained by me. :-)

**Comment by xplshn** [comment] 2023-10-13 18:44
Then, how would it be? I'm a newbie, is there any way we can both access a repo? I was planning on moving from Quake3e to a fork of it which was made specifically for OpenArena, but whenever I try to compile it, it fails. See if it works out for you: https://github.com/Bishop-333/OmegA-engine 

It added all the commits from the original ioquake3 fork that OpenArena uses and is based on Quake3e, so its supposed to be a big +. The thing is, it was made for use in the OmegA mod, so I don't know if all the times it failed for me its because I was trying with the files of the original OA.

**Comment by xplshn** [comment] 2023-10-13 18:45
If you can tell me how I can do to co-own the repo with you, then I guess its okay, I'm not that active here...

**Comment by AsciiWolf** [comment] 2023-10-13 21:02
Well, you can ask the Flathub staff to add me push rights to this repo. Then I would mark my old OpenArena repo as End Of Life with a message that suggest users to use io.github.ec_.Quake3e.OpenArena instead. Then we would change the "OpenArena (Quake3e)" name in appdata file to just "OpenArena". That should be enough. :-)

As a start, you can ask the Flathub staff to give me push rights to this repo. The rest can be done later.

**Comment by xplshn** [comment] 2023-10-15 01:59
@matthiasclasen Could we give push permissions to @AsciiWolf ? Thank you.

**Comment by AsciiWolf** [comment] 2023-10-23 09:34
Thanks, Bartłomiej! The end-of-life-rebase is currently blocked by #58 (and also by my free time and ability to test the "new" OpenArena properly).

**Comment by AsciiWolf** [comment] 2023-10-24 13:08
Another blocker: https://github.com/flathub/io.github.ec_.Quake3e.OpenArena/issues/65

**Comment by AsciiWolf** [comment] 2023-10-24 20:46
All blockers were resolved. I will probably wait for another week, then begin with the EOL process of ws.openarena.OpenArena.

**Comment by Silence410** [comment] 2023-10-25 07:41
HY)) yesterday i downloaded OpenArena and wanted to play on a server but got kicked because i dont get the qkey in OpenArena (Quake3e) but in the "normal" version i get the qkey to play on the server (OS Linux Mint xfce)

**Comment by AsciiWolf** [comment] 2023-10-25 10:26
That's strange, thanks for reporting it! I have tried connecting to multiple online servers and everything worked fine. I have tried it again with more servers and while I can connect to many of them without issues, some do hang on "Awaiting gamestate..." with "Sys_SendPacket: Invalid argument" on stdout. Also, I can confirm that there is no "qkey" or "q3key" file in the config directory.

So, this is most likely another blocker for the ws.openarena.OpenArena EOL.

**Comment by Silence410** [comment] 2023-10-25 10:58
thats the server i tried to connect https://stupidctf.ddns.net/live (/connect geniusctf.duckdns.org:20003) i connect and it starts to downloade the needed files after that i have to quit the game and reopen it after connectin again i get awaitig gamestate and it counts up to 300 (with the message awaiting connection no or bad challange for your adress)

**Comment by Silence410** [comment] 2023-10-25 20:31
Oki found a "fix" for me downloaded the game from the webpage and used OmegA-engine works perfect now

**Comment by xplshn** [comment] 2023-10-26 03:18
I wanted to migrate to OmegA-engine but it didn't work out last time, will try when I have time. I'm very sorry for the lack of attention to this package.

**Comment by Silence410** [comment] 2023-10-26 10:17
Dont worry you did a great job so far i will do my best and help as far as i can :1st_place_medal: :1st_place_medal: :1st_place_medal:

**Comment by AsciiWolf** [comment] 2023-10-26 10:26
I would stick with the Quake3e engine. Changing it to the OmegA one would require to remove (EOL) this Flatpak from Flathub and submit a new one with different namespace instead. And it is not guaranteed that there won't be other problems with the OmegA engine.

The Quake3e engine seems to work great except the qkey bug that will hopefully be possible to fix.

**Comment by xplshn** [comment] 2023-10-27 23:40
@Silence410 Try this https://github.com/flathub/io.github.ec_.Quake3e.OpenArena/pull/77

use the bot builder if the test flatpak is gone when you read this

**Comment by AsciiWolf** [comment] 2023-10-28 00:14
@xplshn If we are going to switch the engine, we need to EOL this Flatpak and submit a new one under a different rDNS name.

**Comment by xplshn** [comment] 2023-10-31 00:43
I'm not interested in switching, but if you are feel free to do so - I play more Quake than play OpenARENA, so by basing the engine on Quake3e and making a flexible wrapper script, users(that includes me!) can play most Id tech 3 based games, including, OpenARENA, Quake3, Urban Terror, etc.

**Comment by xplshn** [comment] 2024-04-05 20:20
@AsciiWolf Are you still interested in the merge? The runtime of the original flatpak is already EOL.

**Comment by AsciiWolf** [comment] 2024-04-05 20:46
Yes, I am! If there are no problems (like the qkey issue) anymore and the Flatpak is mature enough to be a replacement for the original one. :-)

Regarding the 22.08 runtime, I believe that it is not EOL yet, but will be in a few months (after 24.08 gets released).

**Comment by AsciiWolf** [comment] 2024-05-23 21:20
Just a reminder that I am still aware of this ticket and plan to start working on EOLing the original Flatpak and transitioning users to this new one soon. ;-)

**Closed** 2024-05-27 21:54 UTC
